version: 2
jobs:
  build:
    working_directory: ~/nancy
    docker:
      - image: ubuntu:16.04
    steps:
      - run:
          name: Install software
          command: |
            apt-get update && apt-get install -y sudo wget jq \
            && wget get.docker.com -q -S -O - | sudo sh
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Tests
          command: |
            errcount=0
            for f in tests/*.sh; do
              printf "$f\t\t"
              bash "$f" -H
              status=$?
              if [ $status -ne 0 ]; then
                errcount="$(($errcount+1))"
              fi
            done
            if [ $errcount -ne 0 ]; then
              >&2 echo "Oh no! $errcount tests failed"
              exit 1
            fi

